config/routes.rb
Rails.application.routes.draw do

  get 'mind_control/landing'

  get 'mind_control/first'

  get 'mind_control/inventory'

  get 'sessions/new'

  root 'static_pages#home'
  get '/help',    to:  'static_pages#help'
  get '/about',   to:  'static_pages#about'
  get '/contact', to:  'static_pages#contact'
  get '/signup',  to:  'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    before_save {self.email = email.downcase }
    validates :name, presence: true, length: {maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d-]+)*\.[a-z]+\z/i
    VALID_PASSWORD_REGEX = /\A[^\s]{6,}\z/
    validates :email, presence: true, length: {maximum: 255},
                format: { with: VALID_EMAIL_REGEX },
                uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 },
                format: { with: VALID_PASSWORD_REGEX },
                allow_nil: true

    # Returns the hash digest of the given string.
    def User.digest(string)
     cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
     BCrypt::Password.create(string, cost: cost)
    end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def hello
    render html: "Hello World"
  end
  
end

app/controllers/mind_control_controller.rb
class MindControlController < ApplicationController
  def landing
    render 'landing'
  end

  def first
  end

  def inventory
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
	  log_in user
    params[:session][:remember_me] == '1' ? remember(user) : forget(user)
	  redirect_back_or user
    else
    flash.now[:danger] = 'Invalid email/password combination'
    render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end
    
  
  def show
		@user = User.find(params[:id])
	end

  def new
      @user = User.new
  end

  def create
    @user = User.new(user_params)  
    if @user.save
      log_in @user
      flash[:success] = "Hello #{@user.name.capitalize} Welcome to Matthew's Sample Application!" 
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
 #   @user = User.find(params[:id])
  end

  def update
#    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Successfully Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
 
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Your Reality Ends Here"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/mind_control_helper.rb
module MindControlHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
 
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
    # raise       # The tests still pass, so this branch is currently untested.
     user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 180})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
  <small>
   <a href="http://www.railstutorial.org/">Matthew's Brand New Web Adventure!</a>
    by <a href="http://www.google.com/">Matthew Rentz</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Gatekeeper", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Check out!?", mind_control_landing_url %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
     <%= csrf_meta_tags %>
     <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <%= render 'layouts/header' %>
      <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      <%= render 'layouts/footer' %>
     </div>
  </body>
</html>

app/views/mind_control/first.html.erb
\<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
    "http://www.w3.org/TR/html4/strict.dtd">

<html>
    <head>
   <title>'B' Graders </title>
    </head>
    <body>
   <p>Hello <strong>world!</strong><p>
   <br>
   <p>This is my first attempt at a home page.<p>


<p style="font-size: x-small; color: red;">Small Red Font!</p>

<p>One big word in <strong style="font-size: 125%;">BOLD</strong></p>


<p style="text-align: center;">
All text in here will be centered
</p>
<p>Click
<A HREF="http://www.jonstorm.com/html/">Here</A>
to learn how to make your own web page!!!<p>
<BR>

<!--COMMENT : INSERT Home button -->

<A HREF="/index1.html"><IMG STYLE="border: none;" SRC="/webfiles/images/homepage.gif" ALT="Home"></A>

<!--COMMENT : END Home button -->

<div style="text-align: center;"><IMG SRC="/webfiles/images/little google logo.png" 
ALT="/webfiles/images/logo.png"></div> 
<BR>

<a href="http://www.google.com/ncr">Go to Google.com</a></font>
<p><font size=-2>&copy;2009 
<BR>


<!--COMMENT : insert Google image -->

<TABLE ALIGN = "center">
<TR>
<TD><img height=1 width=200></TD>
<TD>
<A HREF="http://www.google.com/ncr"><div style="text-align: center;">
<IMG STYLE="border: none;" SRC="/webfiles/images/google.gif" ALT="Google logo"></A></div>
</TD>
<TD>
<div style="text-align: right;"><p> <---- if you click on it it goes <A NAME="back">to</A> their search page!</p>
</TD>
</TR>
</TABLE>
<br>


<!--COMMENT : INSERT button -->

<form>
<A HREF="/webfiles/clicked_button.htm">
<button name="Button" value="Submit" type="button">Click Me!</button>
</A></form>

<!--COMMENT : END button -->
<p></p> <p></p>
<div style="text-align: left;">
<p><font size=4><strong style="font-size: 100%;">Get <I>this</I></strong>
</p> <font size=4>GOOGLES SEARCH BAR GRAPHICS!</p></div>
<br>

<!--COMMENT : Google srearch bar code -->

<br> <center><form action=/search name=f>
<table id=frame cellpadding=0 cellspacing=10 border: 1px solid black;>
<tr><td nowrap>
<input> <br><font size=-1>Search: 
<input type=radio checked>
<label> the web </label> 
<input type=radio>
<label> pages from Lemuria </label> </font><br>
<input type=submit value="Universe Search" name=btnG></td>
<td valign=top nowrap><font size=-2>&nbsp;<a href=/advanced_search?hl=en>Advanced Search</a>
<br><a href=/preferences?hl=en>Preferences</a>
<br>
<td><img height=1 width=10></td>
</tr></table></td></tr>
<tr><td><table cellpadding=0 cellspacing=0>

<!-- end Google search bar -->

<div style="text-align: center;">
<p><font size=4><strong style="font-size: 125%;">WOW!</strong></p>
<p>I don't believe that I am actually building a real life web page!!!</p></div>
<br>

<!-- background colour changer code -->

<!-- <SCRIPT LANGUAGE="JavaScript"> -->

<div style="text-align: left;">
<p>I've been playing around with a bit of JavaScript too. <br><A HREF="/webfiles/threeInOne.html">Here</A> are a few tricky little gimicky things I pulled of the net.

<TABLE ALIGN = "center">
<TR>
<TD>
<img SRC="/webfiles/images/globe.gif" WIDTH=70 HEIGHT=70 ALIGN=middle
ALT="The world of HTML is at your feet...">
</TD>
<TD>
<div style="text-align: middle;">
<font size=2>
The world of madness has found its feet, <br>
where to and from are niether<br>
But here it stands for you to greet<br>
We know of nothing and never can <br>
Your past is truly over <br>
So forget your mind and take a seat<br>
A new begining you now will meet. <br>
Like a star going super-nova<BR></div>
</TD>
<TD>
<img SRC="/webfiles/images/globe.gif" WIDTH=70 HEIGHT=70 ALIGN=middle
ALT="The world of HTML is at your feet...">
</TD>
</TR>
</TABLE>

<p><font size=4><strong style="font-size: 125%;">WOW!</strong><br>
<br><A HREF="/webfiles/shuttle.htm">This</A>
is the only way to describe my current emotional situation!!!<p>
<BR></br>

<br>hello hello hello</br>
<br>hello hello hello</br>

<TABLE ALIGN = "center">
<TR>
<TD>
The only way to describe this state<br>
Is to liken to analogy<br>
A bird that soars to dizzy heights<br>
Or some other kind of effigy<br>
<br>
The splendour of our idols may<br>
The raw glory of being be, no doubt<br>
But this day is one that must make way<br>
For those of us... who just missed out<br>
</TD>
<TD>
<IMG SRC="/webfiles/images/beach_scene.jpg" ALT="beach_scene.jpg">
</TD>
</TABLE>

<br></br>
<br></br>

<p style="color: red;"><font size=8>Welcome to ....... </FONT></p>
<br></br>
<div style="text-align: center;">
<FONT SIZE="+5"><I><blink> The 'B' Graders Home Page </blink></i></FONT>
<br></br>
<FONT SIZE="2"><B>Please note:</B> If you were viewing this with Mozzila 
Firefox it would be flashing really impressively. 
But it won't work on Explorer.</FONT></div>


<!-- INSERT : Basic Table Template -->

<TABLE CELLSPACING="10" CELLPADDING="10" WIDTH="100%">
<TR VALIGN="Top">
<TD WIDTH="5%">&nbsp;</TD>
<TD WIDTH="90%">
<br><p> </p></br>
<div style="text-align: left;">
<font SIZE="4"> Yes! Unite and lead. The time has come for us to experience our day in the sunshine of our own meritous existence! No longer must we dwell in the shadows and stand in awe of those glorious Sun Beings to whom, with all our striving we may only ever desire to aspire. Sure their exalted exsistence inspires us greatly. They may be great. But <i>we</i> are many. 

<p>&nbsp</p>
<p>&nbsp</p>

<!--COMMENT : mailto form tag -->

<div style="text-align: left;">
<font SIZE="4"> If you have a comment you would like to make about 
this website then you can <a href="mailto:mrentz@tpg.com.au?subject=Feedback for website&body=e.g.Your website is the 2'nd best website ever!">send</a> 
it to me. If you would like I could even post it on here 
and you could become famous! </div>

<!-- END : mailto form tag -->

<p><br><p><br><p><br><p><br><p><br>

<!--COMMENT : INSERT fake counter image -->

<TABLE ALIGN = "center" >
<TR>
<TD style="vertical-align:middle"><font size="2">There have been</TD>
<TD>
<div style="text-align: center;"><IMG style="vertical-align:middle"
SRC="/webfiles/images/counter.png" 
ALT="webfiles//webfiles/images/counter.png"></div> 
</TD>
<TD valign="middle"><font size="2">visitors to this site</TD>
</TR>
</TABLE>
<br>
<!--COMMENT : END fake counter image -->

<p>
<p>

<div style="text-align: left;">
<font SIZE="4">Even though.... strictly speaking you probably won't (become famous because of any association with this site), you see, because if you did then you will be the sort of person who 
is more likely to have been visiting a website that caters for the 
spectacularly successful right about now. But before you go shooting off to find your fortune...... I've got some bad news. It's not going to happen. Leaving this website in search of your dream may really only be going to lead you down the path of illusion. Or, maybe reality, but what's the difference? Or don't you care? Anyway, I'm thrilled to be associated with the second best website ever created of all time so why can't you just at least be happy with your situation? Unless, ofcourse, you are, in which case you would be, successful. Which of course I'm not, but I'm happy. So does that make me successful? Well, I might not be as successful as you but then if I was it would probably make you feel less successful in comparison. Which might make you feel like you could be happier. But is happiness truly going to make you satisfied? The answer is maybe not, or, maybe. In the final analysis nothing will ever compare to the sensation of satisfaction like success will. So what is success anyway?<p> Well, you see, that all depends on whether or not your success is real or implied. Real, of course implying that you really <I>are</I> successful, as opposed to just thinking that you <I>look</I> really successful. Which, again, might just be all you are looking for any way. Yes? I mean, you don't <I>really</I> care how happy you are. Is it not, in fact more likely that you are simply just completely obsessed to within the reaches of your own instiable sanity, with how happy you <I>look?</I> </p><p> Well enough of this inane prattle. I've got the second best website in the universe to build.........</p></TD></div>
<TD WIDTH="5%">&nbsp;</TD>
</TR>
</TABLE>

<!-- END : Basic Table Template -->

<div style="text-align: left;">
<p>Hmmmmmm.......</font></div>

<br></br>

<div style="text-align: left;">
<FONT SIZE="3"><A NAME="beginning">Okay</A>....<br></br>
<p>Lets start by resolving all of the dillemmas 
that seem to be surrounding your exsistence. </p>


<br><p> </p></br>
<br><p> </p></br>


<div style="text-align: left;">
<FONT SIZE="3"> 
<b>Step 1:</b> Don't concern yourself too much with 
what those dillemmas might be, for now.<br> 
<a href="/webfiles/inventory.htm"><b>Step 2</b>:</a> Take stock of the inventory 
which we have available to address what might at 
first seem like a reasonably non-trivial undertaking.<br>
<b>Step 3</b>: Use them like <A NAME="last step" href="webfiles/using_them.htm">this</a>.<br>
<b>Step 4</b>: You are the proud owner of your very own dillemma free exsistence!</font></div>


<br><p> </p></br>
<br><p> </p></br>

<div style="text-align: right;">
<FONT SIZE="3">For God sakes<a href="where_you_were.htm">
get me out of here
</a>!</font></div>


<!-- COMMENT : Link to Ifdawn quabballa page -->

<!-- INSERT : Table  -->

<TABLE ALIGN = "left" >
<TR>
<TD style="vertical-align:left"><font size="8">&nbsp;&nbsp;
&nbsp&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp; </TD>
<TD>
<FONT SIZE="4">
<A HREF="http://ifdawn.com/index.html">This should keep you busy</A> </font>
</TD>
<TD>
<FONT SIZE="1.5"> <---- (b.t.w.) This site is nothing to do with me. 
Whoever wrote this page is WAY more advanced with HTML than me. 
But your <a href="mailto:mrentz@tpg.com.au?subject=Feedback for 
website&body=e.g.'B' graders might really like to .....!">
comments/suggestions</a> for what would make <i>this</i> site better would be very useful.
 </TD>
</TR>
</TABLE>
<br>
<!-- END : table -->

<!-- END : Link to Ifdawn quabballa page -->



<br><p> </p></br>
<br><p> </p></br>
<br><p> </p></br>
<br><p> </p></br>
<br><p> </p></br>

<!-- BEGIN : Fake surprise -->

<div style="text-align: left;">
<font SIZE="+4">MyGod!! ......MyGod!! MyGod!! MyGod!! I don't believe it! I've had 8 visitors since I've started building this site</font><font SIZE="1">.... Oh, no, wait a tick, NOOOOOO!! thats not an eight.</font></div>
<div style="text-align: center;"><IMG style="vertical-align:middle"
SRC="/webfiles/images/zero_counter.png" 
ALT="webfiles//webfiles/images/zero_counter.png"><br>
<FONT SIZE="1"><a href="http://www.webhostingcounter.com/">
REAL website counter!</a></div></font>

<!-- END : Fake surprise -->

<p>
<div style="text-align: center;">
<FONT SIZE="3">Make sure to visit again as I will be updating this site at least once every 24 months. </font></div></p>

    </body>
</html> 

app/views/mind_control/inventory.html.erb
<h1>MindControl#inventory</h1>
<p>Find me in app/views/mind_control/inventory.html.erb</p>

app/views/mind_control/landing.html.erb
<html>
<head>
<title>Server space now active</title>
</head>
<div id="intro">
<body BGCOLOR="#fdbd49" text="#000000">
<center>
<font face="arial">
<P><font size="2"><b>CONGRATULATIONS you have found yourself ......... </b>
<p>
      <%= link_to "HERE", mind_control_first_url, id: "intro" %>


<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>


<BR>
</font>
</center>
</body>
</html>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  <head>
    <title><%= yield(:title) %> | Greetings Jesse!</title>
  </head>           

Some guff to replace placeholder text
  <a href="http://www.google.com">Rails Tutorial help page</a>.
  To get help on this sample app, see the
about the tuorial at the <a href="index1.html">feedback page</a>.

</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  You have made contact. The gatekeeper of your destiny awaits your instructions.
  <a href="http://www.google.com">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
  <body>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
      book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Darkest Web Of Them ALL</h1>

  <h2>
    This is the fun home page for GOD
    <a href="http://www.railstutorial.org/">Link to God</a>
    God's personal Web application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("god.jpg", :size => "350x220", alt: "God"),
            'http://rubyonrails.org/' %>
            
<%= link_to image_tag("sample.gif", :size => "350x220", alt: "Spinner"),
            'http://rubyonrails.org/' %>            
            
<%= link_to image_tag("spinner.gif", :size => "350x220", alt: "goofball"),
            'http://rubyonrails.org/' %>                        
            
                               

app/views/users/_form.html.erb
<h1><%= yield(:heading) %></h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
    
            <%= render 'shared/error_messages' %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    
        <% end %>

  </div>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Are you sure you really want to delete this user?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:heading, 'Update your profile') %>
<% provide(:button_text, 'Save Changes') %>

        <%= render 'form' %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
 <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:heading, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>

        <%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">

  <h1>
    <%= gravatar_for @user %>
    <%= @user.name.capitalize %>
  </h1>


    </section>
  </aside>
</div>